site_name: My Favourite Recipes
site_url: https://example.com/
site_description: This contains all of my favourite recipes
site_author: Matt Holder
site_dir: docs/
docs_dir: staticFiles/
theme:
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  icon:
    logo: material/food 
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search
  - offline
  - with-pdf
  - tags:
      tags_file: tags.md